---
apiVersion: v2
name: graphql-hive
version: 1.0.0
description: Deploy hive
home: https://docs.graphql-hive.com/self-hosting/get-started
dependencies:
  - name: clickhouse
    version: 1.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: kafka
    version: 19.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: hive-app
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-app.enabled
  - name: hive-emails
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-emails.enabled
  - name: hive-schema
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-schema.enabled
  - name: hive-server
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-server.enabled
  - name: hive-storage
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-storage.enabled
  - name: hive-tokens
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-tokens.enabled
  - name: hive-usage
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-usage.enabled
  - name: hive-usage-ingestor
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-usage-ingestor.enabled
  - name: hive-webhooks
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: hive-webhooks.enabled
  - name: supertokens
    version: 1.0.0
    repository: https://diabolocom.github.io/graphql-hive/helm-subcharts/
    condition: supertokens.enabled
