annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "When using existingSecret the path to the file was not added to n8n.configFiles in the helpers."
      links:
        - name: "PR #63"
          url: https://github.com/8gears/n8n-helm-chart/pull/63
apiVersion: v2
appVersion: 1.22.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.6.1
description: A Kubernetes Helm chart for n8n a free and open fair-code licensed node
  based Workflow Automation Tool. Easily automate tasks across different services.
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
- Workflow Automation
- Workflow
- iPaaS
- integration-framework
- low-code-plattform
- low-code
maintainers:
- name: Vadim Bauer
name: n8n
sources:
- https://github.com/n8n-io/n8n
- https://n8n.io/
type: application
version: 0.20.2
