{{- $url := printf "usage-%s" .Values.global.appBaseUrl }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.namespace }}-usage-ingress
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: private
  rules:
    - host: {{ $url }}
      http:
        paths:
          - backend:
              service:
                name: usage-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
{{- if .Values.ingress.useTls }}
  tls:
    - hosts:
        - {{ $url }}
      secretName: usage-hive-k8s
{{- end }}